/*
 * Copyright (C) 2013 Silas Schwarz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package truetype;

import awtX.XFileChooser;
import com.XCodeMT.chromeTabs.ITab;
import com.XCodeMT.chromeTabs.jhrome.JhromeTabBorderAttributes;
import java.awt.Color;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.UndoManager;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author silas
 */
public class FileView extends javax.swing.JPanel {
    private ITab tab;
    private File file;
    private XFileChooser fileChooser;
    protected UndoManager undo = new UndoManager();
    TTabbedPaneWindow window;

    /**
     * Creates new form FileView
     */
    public FileView(ITab tab, TTabbedPaneWindow window) {
        initComponents();
        textArea.setOpaque(false);
        textAreaScroller.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0, 0), 2));
        textArea.setBackground(JhromeTabBorderAttributes.SELECTED_BORDER.topColor);
        this.tab = tab;
        this.tab.setContent(this);
        fileChooser = new XFileChooser();
        file = null;
        textArea.getDocument().addUndoableEditListener(new MyUndoableEditListener());
        this.window = window;
    }
    
    public UndoManager getUndo() {
        return undo;
    }
    
    protected class MyUndoableEditListener implements UndoableEditListener {
        
        @Override
        public void undoableEditHappened(UndoableEditEvent e) {
            //Remember the edit and update the menus
            undo.addEdit(e.getEdit());
            window.getUndoAction().update();
            window.getRedoAction().update();
        }
        
    }  
    
    public void open() {
        if (fileChooser.showOpenDialog()) {
            file = fileChooser.getFile();
            update();
        }
    }
    
    public void save() {
        if (file == null) {
            saveAs();
        } else {
            try {
                FileUtils.writeStringToFile(file, textArea.getText());
            } catch(IOException e) {
                e.printStackTrace();
            }
        }
        update();
    }
    
    public void saveAs() {
        if (fileChooser.showSaveDialog()) {
            file = fileChooser.getFile();
            save();
        }
    }
    
    public void update() {
        if (file != null) {
            try {
                textArea.setText(FileUtils.readFileToString(file));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        tab.setTitle(file.getName());
    }
    
    public JTextArea getTextArea() {
        return textArea;
    }
    
    public void setTextArea(JTextArea textArea) {
        this.textArea = textArea;
    }
    
    public JScrollPane getTextAreaScroller() {
        return textAreaScroller;
    }
    
    public void setTextAreaScroller(JScrollPane textAreaScroller) {
        this.textAreaScroller = textAreaScroller;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    
    public File getFile() {
        return file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaScroller = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        textArea.setBackground(new java.awt.Color(255, 255, 0));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textArea.setRows(5);
        textAreaScroller.setViewportView(textArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textAreaScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, textAreaScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textAreaScroller;
    // End of variables declaration//GEN-END:variables
}
